### PR TITLE
Ability to add defaultParameters

### PR DESCRIPTION
**Pull request by dannyhaak**
We have an API construction where we need to add in the workspaceId (like a tenant identifier) in every request in the path:
`http://server/api/<workspaceId>/do-something`

This is currently handled by passing in the workspaceId as parameter in every request, but it would be great if we can just set defaultParameters when creating an OpenAPIClient.

```
const api = new OpenAPIClientAxios({
    definition: 'http://localhost:5000/swagger/private/swagger.json',
    defaultParameters: {
        workspaceId: '63e90965-0797-4393-8f5d-d2e8fae0e8d0'
    }
});
```

### CODE REVIEW

**Comment by dannyhaak** [comment]
@anttiviljami Can you have a look at my pull request? Open to add or change things when requested. Thanks :).

**Comment by anttiviljami** [comment]
Hi @dannyhaak, sorry but I disagree with this implementation. Something about setting a global parameter for all requests doesn't sit well with me.

I could however go for a more generic / flexible approach, e.g.

```typescript
const api = new OpenAPIClientAxios({
  definition,
  transformOperationMethods: (operationMethod) =>
     (...args: OperationMethodArguments) => operationMethod({
       workspaceId: '63e90965-0797-4393-8f5d-d2e8fae0e8d0',
       ...args[0],
     },
     args[1],
     args[2],
   )
  }
});
```

Happy to merge an implementation of something like the above ☝️ 

What do you think @dannyhaak ?

**Comment by dannyhaak** [comment]
I would agree this is a better implementation, but I have a challenge in understand why you want to have a return calling the operationMethod function. What is that function? And why is it necessary? I was thinking more in the line of:

```
const transformOperationMethods = (operationMethod: Operation) => {
      return (params: any, body: any, requestConfig: any): OperationMethodArguments => {
        // set default workspaceId for all operations
        params.workspaceId = '63e90965-0797-4393-8f5d-d2e8fae0e8d0';
        return [params, body, config];
      };
    };
```
(Need to fix TypeScript types)

You can still base the transformation on the actual operation.

Basically all information you want to transform is available in the `args` parameter in `getAxiosConfigForOperation`.

```
    const transformedArgs: OperationMethodArguments = this.transformOperationMethods(operation)(...args);
    const request = this.getRequestConfigForOperation(operation, transformedArgs);
```

What am I missing compared to your example?

**Comment by anttiviljami** [comment]
My idea was to have a simple transform function for the operation method. 

It takes in the unmodified operation method, a function. 

And returns the modified operation method, a different function. (Usually a wrapper). 

What you’re describing would be a transform, but applied only to the parameters of the operation methods. A slightly different idea.

**Comment by anttiviljami** [comment]
I like the idea of also providing the Operation object as context to the transformer 👍👍

**Comment by dannyhaak** [comment]
So it basically becomes (where `transformationOperationMethod` becomes a constructor parameter):

```
private createOperationMethod = (operation: Operation): UnknownOperationMethod => {
    const transformOperationMethod = (operationMethod: UnknownOperationMethod, operationA: Operation): UnknownOperationMethod => {
      return (params, body, config) => {
        // set default workspaceId for all operations
        params.workspaceId = '63e90965-0797-4393-8f5d-d2e8fae0e8d0';
        return operationMethod(params, body, config);
      };
    };

    const originalOperationMethod = async (...args: OperationMethodArguments) => {
      const axiosConfig = this.getAxiosConfigForOperation(operation, args);
      // do the axios request
      return this.client.request(axiosConfig);
    };

    return transformOperationMethod(originalOperationMethod, operation);
  };
```

Forgive me my TypeScript ignorance, but why do I get the following error:
```
 Property 'workspaceId' does not exist on type 'Parameters<UnknownParamsObject>'.
 Property 'workspaceId' does not exist on type 'string'.
```

**Comment by dannyhaak** [comment]
Never mind, not relevant in the JS code. There, I fixed it :). This should be to your liking, and hopefully approval :).

**Comment by anttiviljami** [comment]
Looks fantastic! I'll still need to add some DOCS and a test for this.

Let me know if you're willing to support with that to get this merged :)

**Comment by dannyhaak** [comment]
No worries, let me add documentation and tests as well.

**Comment by dannyhaak** [comment]
One more thing about naming, to get your opinion: we have `transformOperationName` but now added `transformOperationMethods`, wouldn't it make more sense to use `transformOperationMethod`, the non-plural version?

**Comment by dannyhaak** [comment]
@anttiviljami Gentle nudge :)

**Comment by anttiviljami** [comment]
Hi @dannyhaak. Thanks for the nudge 😊

Looks awesome already! 🤩 Thanks so much. 

Yeah I’d agree with changing to the singular for consistency 👍

Anothet thing (I can take care of it after the merge) would be to move the docs you added to the DOCS.md. These are advanced use cases that I don’t think need to be on the main README

**Comment by anttiviljami** [comment]
Let’s change the name of the opt and I’ll merge afterwards 👌

**Comment by dannyhaak** [comment]
I missed the docs.md, no worries: added it in in the structure there. Should be good to go now, right?

**Pull request merged**
