### PR TITLE
fix: typegen schemaRef convertion and path parameters

### PR DESCRIPTION
**Pull request by npdev453**
fixes https://github.com/anttiviljami/openapi-client-axios/issues/92
fixes https://github.com/anttiviljami/openapi-client-axios/issues/91

### CODE REVIEW

**Review by briceruzand — APPROVED** [review]
That fix #91
:+1:

**Comment by briceruzand** [comment]
Any news on to merge that PR ?

**Comment by npdev453** [comment]
@anttiviljami

**Comment by anttiviljami** [comment]
Thanks, LGTM @npdev453 !

**Pull request merged**
