### PR TITLE
feat/add user-agent header to schema http resolver

### PR DESCRIPTION
**Pull request by alleksei37**
Typegen module is not using User-Agent header which may cause issues with some proxies that require this header. The content of the header is not that important.
Having the User-Agent header also helps to distinguish Typegen requests during CI/CD build step from all other client side requests.
I believe that Typegen can be considered as a user agent. The definition of the User Agent can be found here:
https://www.rfc-editor.org/rfc/rfc9110.html#name-user-agents
Per RFC 9110 (HTTP Semantics) A user agent **SHOULD** send a User-Agent header field in each request unless specifically configured not to do so.
https://www.rfc-editor.org/rfc/rfc9110.html#name-user-agent

P.S.
Ideally, we should also include the current version of the package as part of the User-Agent header but it would require some more work like adding an additional build step to run a tokenizer to set the version after TS compilation.

### CODE REVIEW

**Comment by anttiviljami** [comment]
LGTM ✅

> Ideally, we should also include the current version of the package as part of the User-Agent header but it would require some more work like adding an additional build step to run a tokenizer to set the version after TS compilation.

Or, we could just parse the version on runtime from package.json, no?

**Review by anttiviljami — APPROVED** [review]

**Comment by alleksei37** [comment]
> LGTM ✅
> 
> > Ideally, we should also include the current version of the package as part of the User-Agent header but it would require some more work like adding an additional build step to run a tokenizer to set the version after TS compilation.
> 
> Or, we could just parse the version on runtime from package.json, no?

Yeah, I think we could do that too but during build time only since we don't have package.json at runtime. 🤔

**Comment by anttiviljami** [comment]
Why is package.json not available during runtime?

**Comment by anttiviljami** [comment]
@alleksei37 I’m confused. This is typegen you’re adding the user agent header for. It’s a command line tool. Doesn’t run in the browser. 

This change doesn’t affect user agent in the actual openapi client instance

**Comment by alleksei37** [comment]
> @alleksei37 I’m confused. This is typegen you’re adding the user agent header for. It’s a command line tool. Doesn’t run in the browser.
> 
> This change doesn’t affect user agent in the actual openapi client instance

Oh, yes! You are 100% right! I made a wrong mental connection between the client in the browser and this package! Please disregard my previous comment about the issues with parsing package.json 🤦🏻‍♂️

**Comment by alleksei37** [comment]
@anttiviljami I'm sorry for pinging you again, but when this PR can be merged? It looks like I don't have permission for that. Thanks!

**Comment by anttiviljami** [comment]
Hi @alleksei37 ! Thanks for your work, I'm ready to merge ✅

**Pull request merged**
